export enum GameEvent {
    LOAD_START = "LOAD_START",
    LOAD_COMPLETE = "LOAD_COMPLETE",
    SETUP_COMPLETE = "SETUP_COMPLETE",
};

export enum MapEvent {
    REQUEST_MAP_LOAD = "REQUEST_MAP_LOAD",
    MAP_LOAD_START = "MAP_LOAD_START",
    MAP_LOAD_COMPLETE = "MAP_LOAD_COMPLETE",
};
